#!/usr/bin/env python
import roslib
roslib.load_manifest('exercise4')
import rospy
from std_msgs.msg import String
from sound_play.libsoundplay import SoundClient

class Speaker():

    def say_callback(self, sentence):
        s = str(sentence)
        self.soundhandle.say(s)
        print("Saying {}".format(s))

    def __init__(self):
        rospy.init_node('speaker', anonymous=True)
        self.soundhandle = SoundClient()
        _ = rospy.Subscriber("speaker/say", String, self.say_callback)


if __name__ == '__main__':
    _ = Speaker()
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")